version: 2

processors:
  - json_parse:
      fields:
        - message, data
      ignore_missing: true
  - simple_extract:
      fields:
        - data, time_us
      key: "time_us"
      ignore_missing: false
  - epoch:
      fields:
        - time_us
      resolution: microsecond
  - select:
      fields:
        - time_us
        - data

transform:
  - fields:
      - time_us
    type: epoch, us
    index: timestamp
